language: node_js
node_js:
  - "node"
  - "8"
before_script:
  - npm run bootstrap
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
cache:
  directories:
    - node_modules
